site_name: Grovelab
pages:
- Home: 'index.md'
- Linux Sysadmin: 'linux-sysadmin.md'
- Linux Commands: 'linux-commands.md'
- Linux Tools Commands: 'linuxtools-commands.md'
- Text (awk sed grep etc ): 'text.md'
- MySQL : 'mysql.md'
- Apache : 'apache.md'
- Git : 'git.md'
- Linux Desktop : 'linux-desktop.md'
- MacOS : 'macos.md'
- Linux Tools and Terms : 'opensouce-tools-and-terms.md'
- RHCE: 'rhce.md'

theme: readthedocs
