site_name: Grovelab
pages:
- Home: 'index.md'
- Linux sysadmin: 'linux-sysadmin.md'
- Linux commands: 'linux-commands.md'
- Linux tools commands: 'linuxtools-commands.md'
- Text (awk sed grep etc ): 'text.md'
- MySQL : 'mysql.md'
- Apache : 'apache.md'
- Git : 'git.md'
- Linux desktop : 'linux-desktop.md'
- MacOS : 'macos.md'
- RHCE: 
  - Resources: 'RHCE/resources.md'
  - Useful commands: 'RHCE/useful-cmds.md'
  - Create a partition - lvm: 'RHCE/lvm-partition.md'
  - Networking - nmcli: 'RHCE/nmcli.md'
  - firewall-cmd: 'RHCE/firewall-cmd.md'
  - Client auth with kerberos & ldap: 'RHCE/client-auth-kerb-ldap.md'
  - iSCSI Target and Initiator: 'RHCE/iscsi.md'
  - Kerborized NFS: 'RHCE/nfs.md'

#theme: windmill
#theme: material
theme: readthedocs

#Broken themes (To many pages):
#theme: cinder
#theme: bootstrap
#theme: windmill-dark
# Theme bootswatch:
#theme: yeti
#or
#theme: amelia
#extra:
    #theme_inverse: true
