site_name: Grovelab
pages:
- Home: 'index.md'
- Linux sysadmin: 'linux-sysadmin.md'
- Linux commands: 'linux-commands.md'
- Linux tools commands: 'linuxtools-commands.md'
- Text (awk sed grep etc ): 'text.md'
- MySQL : 'mysql.md'
- Apache : 'apache.md'
- Git : 'git.md'
- Linux desktop : 'linux-desktop.md'
- MacOS : 'macos.md'
- RHCE: 
  - Resources: 'RHCE/resources.md'
  - Useful commands: 'RHCE/useful-cmds.md'
  - Networking: 'RHCE/networking.md'
  - firewall-cmd: 'RHCE/firewall-cmd.md'
  - Client auth with kerberos & ldap: 'RHCE/client-auth-kerb-ldap.md'

theme: readthedocs
